[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
maze-playground = {path = ".."}
rand = { version = "0.8.5", default-features = false }
rand_core = { version = "0.6.4", features = ["alloc"] }

[lib]
crate-type = ["cdylib", "rlib"]

