name: Build and Deploy to Google Cloud Storage
on:
  push:
    branches: ["main"]
  workflow_dispatch:
env:
  GCP_TOKEN: ${{ secrets.GCP_TOKEN }}
jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install rust wasm
        run: rustup target add wasm32-unknown-unknown
      - name: Install wasm-opt
        run: sudo apt-get install binaryen
      - name: Checkout
        uses: actions/checkout@v3
      - name: build and deploy
        run: ./build.bash
