name: Build and Deploy to Google Cloud Storage
on:
  push:
    branches: ["main"]
  workflow_dispatch:
env:
  GCP_TOKEN: ${{ secrets.GCP_TOKEN }}
jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Install rust wasm
        run: rustup target add wasm32-unknown-unknown
      - name: Install wasm-opt
        run: apt-get update && apt-get install binaryen --assume-yes --no-install-recommends --no-install-suggests
      - name: Checkout
        uses: actions/checkout@v4
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "maze-playground"
          workload_identity_provider: "projects/206430360926/locations/global/workloadIdentityPools/github/providers/my-repo"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
      - name: build and deploy
        run: ./build-and-release.bash
